import{S as m,a as p,i as l}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const h=new m(".gallery a",{scaleImageToRatio:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});async function g(o){o.forEach(e=>{const n=`
            <div class="card">
                <a href="${e.webformatURL}">
                    <img src="${e.webformatURL}" alt="${e.tags}">
                </a>
                <p>Likes: ${e.likes}</p>
                <p>Views: ${e.views}</p>
                <p>Comments: ${e.comments}</p>
                <p>Downloads: ${e.downloads}</p>
            </div>
        `;gallery.insertAdjacentHTML("beforeend",n)}),o[0].totalHits,h.refresh()}const u=document.getElementById("loader"),f=document.querySelector(".gallery");let a=1,c="";document.getElementById("searchForm").addEventListener("submit",async o=>{o.preventDefault();const e=document.getElementById("searchInput");e&&(a=1,c=e.value.trim(),f.innerHTML="",await y(c))});async function y(o){try{w();const e=await p.get(`https://pixabay.com/api/?key=28194821-49041d995ecd04735d9e20d11&q=${o}&page=${a}&per_page=15`);d();const n=e.data.hits,s=e.data.totalHits;if(n.length===0){L();return}if(g(n),n.length===0){l.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",color:"red"});return}b(),v(s)}catch(e){d(),handleError(e)}}function w(){u.style.display="block"}function d(){u.style.display="none"}function L(){l.info({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomCenter",color:"red"})}function b(){loadMoreBtn.style.display=f.childElementCount>0?"block":"none"}function E(){loadMoreBtn.style.display="none"}function v(o){o-a*15<=0&&(E(),M())}function M(){l.show({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",color:"blue"})}async function B(o){return new Promise(e=>{window.scrollBy({top:o,behavior:"smooth"}),window.addEventListener("scroll",function n(){window.removeEventListener("scroll",n),e()})})}loadMoreBtn.addEventListener("click",async()=>{a++,await y(c),await I()});async function I(){const o=document.querySelector(".gallery .card").getBoundingClientRect().height;await B(window.scrollY+o)}
//# sourceMappingURL=commonHelpers.js.map
